# Generated by Django 4.2 on 2023-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0002_post_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resume',
            field=models.TextField(max_length=500),
        ),
    ]
