# Generated by Django 4.2 on 2023-04-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0003_alter_post_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_on',
            new_name='created_at',
        ),
    ]
