# Generated by Django 4.2 on 2023-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0004_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.TextField(choices=[('Bulgaria', 'Bulgaria'), ('Abroad', 'Abroad')], default='Bulgaria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft'),
        ),
    ]
