# Generated by Django 4.2 on 2023-04-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0008_mailmessage_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
