# Generated by Django 4.2 on 2023-04-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0009_alter_subscribers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
