# Generated by Django 4.2 on 2023-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0012_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
