# Generated by Django 4.2 on 2023-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0013_placesvisited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placesvisited',
            options={'verbose_name_plural': 'Places Visited'},
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
