# Generated by Django 4.2 on 2023-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0015_alter_placesvisited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesvisited',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='place_status',
            field=models.TextField(choices=[('Loved', 'Loved'), ('Home', 'Home'), ('Default', 'Default')], default='Default'),
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='resume',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='tooltip',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
