# Generated by Django 4.2 on 2023-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0016_placesvisited_image_placesvisited_place_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesvisited',
            name='place_status',
            field=models.CharField(choices=[('Loved', 'Loved'), ('Home', 'Home'), ('Default', 'Default')], default='Default', max_length=7),
        ),
    ]
