# Generated by Django 4.2 on 2023-04-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0017_alter_placesvisited_place_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesvisited',
            name='place_status',
            field=models.CharField(choices=[('Loved', 'Loved'), ('Home', 'Home'), ('Default', 'Default'), ('Wanted', 'Wanted')], default='Default', max_length=7),
        ),
    ]
