# Generated by Django 4.2 on 2023-04-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coco', '0018_alter_placesvisited_place_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesvisited',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
